In [2]:
import torch

/home/dai/anaconda3/envs/dxt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
print(torch.cuda.is_available())

True


In [7]:
b1 = torch.rand([2,3])
print(b1)

b2 = torch.rand([2,3])
print(b2)
a = []
a.append(b1)
a.append(b2)
c = torch.stack(a)
print(c.size())
print(c)

tensor([[0.3854, 0.1021, 0.6359],
        [0.1453, 0.4799, 0.9796]])
tensor([[0.5304, 0.8479, 0.1234],
        [0.5257, 0.5502, 0.9305]])
torch.Size([2, 2, 3])
tensor([[[0.3854, 0.1021, 0.6359],
         [0.1453, 0.4799, 0.9796]],

        [[0.5304, 0.8479, 0.1234],
         [0.5257, 0.5502, 0.9305]]])


In [2]:
item=[]
item.append({'a':1,'b':2})
item.append({'a':3,'b':5})
print(item)

[{'a': 1, 'b': 2}, {'a': 3, 'b': 5}]


In [14]:
from transformers import AutoTokenizer

/Users/dai/opt/anaconda3/envs/dxt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [35]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sentences = ['LIHUA IS','hinata bb','xuxu','f','sdffgter wergffg']
sentences = tokenizer(sentences, padding=True)
ss = torch.tensor(sentences['input_ids'])
print(ss)
emb = torch.nn.Embedding(30522,100)
e = emb(ss)
print(e)
print(e.size())

ValueError: expected sequence of length 5 at dim 1 (got 6)