In [2]:
import torch

/home/dai/anaconda3/envs/dxt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
print(torch.cuda.is_available())

True


In [7]:
b1 = torch.rand([2,3])
print(b1)

b2 = torch.rand([2,3])
print(b2)
a = []
a.append(b1)
a.append(b2)
c = torch.stack(a)
print(c.size())
print(c)

tensor([[0.3854, 0.1021, 0.6359],
        [0.1453, 0.4799, 0.9796]])
tensor([[0.5304, 0.8479, 0.1234],
        [0.5257, 0.5502, 0.9305]])
torch.Size([2, 2, 3])
tensor([[[0.3854, 0.1021, 0.6359],
         [0.1453, 0.4799, 0.9796]],

        [[0.5304, 0.8479, 0.1234],
         [0.5257, 0.5502, 0.9305]]])


In [2]:
item=[]
item.append({'a':1,'b':2})
item.append({'a':3,'b':5})
print(item)

[{'a': 1, 'b': 2}, {'a': 3, 'b': 5}]


In [14]:
from transformers import AutoTokenizer

/Users/dai/opt/anaconda3/envs/dxt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sentences = ['LIHUA IS','hinata bb','xuxu','f','sdffgter wergffg']
sentences = tokenizer(sentences, padding=True)
ss = torch.tensor(sentences['input_ids'])
print(ss)
emb = torch.nn.Embedding(30522,100)
e = emb(ss)
print(e)
print(e.size())

In [11]:
from simcse import SimCSE
from sentence_transformers import SentenceTransformer,util
model = SimCSE("princeton-nlp/sup-simcse-bert-base-uncased")
model_b = SentenceTransformer('all-MiniLM-L6-v2',device='cuda')

12/13/2022 15:04:18 - INFO - sentence_transformers.SentenceTransformer -   Load pretrained SentenceTransformer: all-MiniLM-L6-v2
Downloading: 100%|██████████| 1.18k/1.18k [00:00<00:00, 1.34MB/s]
Downloading: 100%|██████████| 190/190 [00:00<00:00, 193kB/s]
Downloading: 100%|██████████| 10.6k/10.6k [00:00<00:00, 7.87MB/s]
Downloading: 100%|██████████| 116/116 [00:00<00:00, 138kB/s]
Downloading: 100%|██████████| 39.3k/39.3k [00:00<00:00, 193kB/s] 
Downloading: 100%|██████████| 90.9M/90.9M [00:02<00:00, 43.2MB/s]
Downloading: 100%|██████████| 53.0/53.0 [00:00<00:00, 66.8kB/s]
Downloading: 100%|██████████| 112/112 [00:00<00:00, 113kB/s]
Downloading: 100%|██████████| 466k/466k [00:00<00:00, 579kB/s] 
Downloading: 100%|██████████| 350/350 [00:00<00:00, 455kB/s]
Downloading: 100%|██████████| 13.2k/13.2k [00:00<00:00, 12.4MB/s]
Downloading: 100%|██████████| 232k/232k [00:00<00:00, 279kB/s]  
Downloading: 100%|██████████| 349/349 [00:00<00:00, 468kB/s]


In [14]:
sentences_a = ['A woman is reading.', 'A man is playing a guitar.']
sentences_b = ['He plays guitar.', 'A woman is writing a biography.']
embeddings1 = model_b.encode(sentences_a, convert_to_tensor=True)
embeddings2 = model_b.encode(sentences_b, convert_to_tensor=True)
cosine_scores = util.cos_sim(embeddings1, embeddings2)
similarities = model.similarity(sentences_a, sentences_b)
print('similarities',similarities)
print('cosine_score',cosine_scores)

100%|██████████| 1/1 [00:00<00:00, 64.07it/s]

similarities [[ 0.01262089  0.6344101 ]
 [ 0.89384246 -0.01970754]]
cosine_score tensor([[-0.0785,  0.6115],
        [ 0.8333, -0.0118]], device='cuda:0')
