In [1]:
import torch

In [2]:
a = torch.tensor([[1,2,3],[3,4,5]])
print(a.size())

torch.Size([2, 3])


In [38]:
b = a.squeeze(-1)
print(a.squeeze(-1))
print(b.squeeze(-1))
print(a)

tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [3, 4, 5]])


In [40]:
item={}
item['aa'] = 10
item['bb'] = 'abab'
print(item)

{'aa': 10, 'bb': 'abab'}


In [14]:
from transformers import AutoTokenizer

/Users/dai/opt/anaconda3/envs/dxt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [35]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sentences = ['LIHUA IS','hinata bb','xuxu','f','sdffgter wergffg']
sentences = tokenizer(sentences, padding=True)
ss = torch.tensor(sentences['input_ids'])
print(ss)
emb = torch.nn.Embedding(30522,100)
e = emb(ss)
print(e)
print(e.size())

ValueError: expected sequence of length 5 at dim 1 (got 6)