In [2]:
import torch

/home/dai/anaconda3/envs/dxt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [1]:
from simcse import SimCSE
from sentence_transformers import SentenceTransformer,util
model = SimCSE("princeton-nlp/sup-simcse-bert-base-uncased")
model_b = SentenceTransformer('all-MiniLM-L6-v2',device='cuda')

Downloading:   0%|          | 0.00/689 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/252 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

KeyboardInterrupt: 

In [ ]:
datadir = "./dataset/Wiki10-31K"
texts = []
pre_labels=[]
true_labels =[]
with open(datadir+"test_texts.txt",'r+') as f:
    for row in f:
        texts.append(row.strip())
with open(datadir+"test_labels.txt",'r+') as f:
    for row in f:
        true_labels.append(row.strip().split(", "))
with open(datadir+"res/test_combine_labels_t5lbi","r+") as f:
    for row in f:
        pre_labels.append(row.strip().split(", "))

In [3]:
print(torch.cuda.is_available())

True


In [7]:
b1 = torch.rand([2,3])
print(b1)

b2 = torch.rand([2,3])
print(b2)
a = []
a.append(b1)
a.append(b2)
c = torch.stack(a)
print(c.size())
print(c)

tensor([[0.3854, 0.1021, 0.6359],
        [0.1453, 0.4799, 0.9796]])
tensor([[0.5304, 0.8479, 0.1234],
        [0.5257, 0.5502, 0.9305]])
torch.Size([2, 2, 3])
tensor([[[0.3854, 0.1021, 0.6359],
         [0.1453, 0.4799, 0.9796]],

        [[0.5304, 0.8479, 0.1234],
         [0.5257, 0.5502, 0.9305]]])


In [2]:
item=[]
item.append({'a':1,'b':2})
item.append({'a':3,'b':5})
print(item)

[{'a': 1, 'b': 2}, {'a': 3, 'b': 5}]


In [14]:
from transformers import AutoTokenizer

/Users/dai/opt/anaconda3/envs/dxt/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sentences = ['LIHUA IS','hinata bb','xuxu','f','sdffgter wergffg']
sentences = tokenizer(sentences, padding=True)
ss = torch.tensor(sentences['input_ids'])
print(ss)
emb = torch.nn.Embedding(30522,100)
e = emb(ss)
print(e)
print(e.size())

In [14]:
sentences_a = ['A woman is reading.', 'A man is playing a guitar.']
sentences_b = ['He plays guitar.', 'A woman is writing a biography.']
embeddings1 = model_b.encode(sentences_a, convert_to_tensor=True)
embeddings2 = model_b.encode(sentences_b, convert_to_tensor=True)
cosine_scores = util.cos_sim(embeddings1, embeddings2)
similarities = model.similarity(sentences_a, sentences_b)
print('similarities',similarities)
print('cosine_score',cosine_scores)

100%|██████████| 1/1 [00:00<00:00, 64.07it/s]

similarities [[ 0.01262089  0.6344101 ]
 [ 0.89384246 -0.01970754]]
cosine_score tensor([[-0.0785,  0.6115],
        [ 0.8333, -0.0118]], device='cuda:0')
